name: Publish Docker image

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Настройка Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Авторизация в YC
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "${SERVICE_ACCOUNT_KEY}" | docker login --username oauth --password-stdin cr.yandex
      - name: Закидываем образ в YC
        env:
          IMAGE_NAME: cr.yandex/crpsf58ad0hhb5dj9q2f/siadev
        run: |
          docker buildx build --push --tag $IMAGE_NAME:${{ github.ref_name }} .

  deploy:
    needs: bluid-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.4
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
          IMAGE_NAME: cr.yandex/crpsf58ad0hhb5dj9q2f/siadev
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo "${SERVICE_ACCOUNT_KEY}" | docker login --username oauth --password-stdin cr.yandex
            docker pull cr.yandex/$IMAGE_NAME/your-image-name:latest
            docker stop your-container-name || true
            docker rm your-container-name || true
            docker run -d --name your-container-name -p 80:80 $IMAGE_NAME:${{github.ref_name}}:latest