name: Publish Docker image & run it on VM & run it on VM

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Настройка Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Авторизация в YC
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "${SERVICE_ACCOUNT_KEY}" | docker login --username oauth --password-stdin cr.yandex
      - name: Закидываем образ в YC
        env:
          IMAGE_NAME: cr.yandex/crpsf58ad0hhb5dj9q2f/siadev
        run: |
          docker buildx build --push --tag $IMAGE_NAME:${{ github.ref_name }} .

  deploy:
    needs: build-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
          IMAGE_NAME: cr.yandex/crpsf58ad0hhb5dj9q2f/siadev
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          envs: SERVICE_ACCOUNT_KEY, IMAGE_NAME
          script: |
            echo "${SERVICE_ACCOUNT_KEY}" | docker login --username oauth --password-stdin cr.yandex
            docker pull $IMAGE_NAME:${{ github.ref_name }}
            docker stop siadev.ru || true
            docker rm siadev.ru|| true
            docker run -d --name siadev.ru -p 80:80 $IMAGE_NAME:${{ github.ref_name }}