name: Publish Docker image & run it on VM & run it on VM

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
    steps:
      - name: Берем код
        uses: actions/checkout@v4
      
      - name: Настройка Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Авторизация в YC
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
        run: |
          echo "${SERVICE_ACCOUNT_KEY}" | docker login --username oauth --password-stdin cr.yandex

      - name: Кэшируем слои докера
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
          ${{ runner.os }}-buildx-
      - name: Закидываем образ в YC
        uses: docker/build-push-action@v2
        build-args: |
          SSL_CERT=${{ secrets.SSL_CERT }}
          SSL_KEY=${{ secrets.SSL_KEY }}
        env: 
          IMAGE_NAME: cr.yandex/crpsf58ad0hhb5dj9q2f/siadev
        with:
          context: .
          push: true
          tags: $IMAGE_NAME:${{ github.ref.name }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

  deploy:
    needs: build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Берем код
        uses: actions/checkout@v4

      - name: Деплоим через SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          SERVICE_ACCOUNT_KEY: ${{ secrets.YC_SERVICE_ACCOUNT_KEY }}
          IMAGE_NAME: cr.yandex/crpsf58ad0hhb5dj9q2f/siadev
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          envs: SERVICE_ACCOUNT_KEY, IMAGE_NAME
          script: |
            echo "${SERVICE_ACCOUNT_KEY}" | docker login --username oauth --password-stdin cr.yandex
            docker pull $IMAGE_NAME:${{ github.ref_name }}
            docker stop siadev.ru || true
            docker rm siadev.ru|| true
            docker run -d --name siadev.ru -p 80:80 $IMAGE_NAME:${{ github.ref_name }}